# Generated by Django 3.1.6 on 2021-02-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosObtenidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100)),
                ('email', models.EmailField(default='', max_length=100)),
                ('celular', models.CharField(default='', max_length=100)),
                ('credencial', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('departamento', models.CharField(default='', max_length=100)),
                ('barrio', models.CharField(default='', max_length=100)),
                ('municipio', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
    ]
