# Generated by Django 3.1.6 on 2021-02-19 02:06

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(default='', max_length=200, verbose_name='Titulo del blog')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_blog')),
                ('descripcion_breve', models.TextField(default='', verbose_name='Descripcion Breve')),
                ('contenido_blog', ckeditor.fields.RichTextField(verbose_name='Contenido del blog')),
                ('imagen_blog', models.URLField(default='', max_length=600, verbose_name='URL de la Imagen')),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
