# Generated by Django 3.1.6 on 2021-02-26 19:55

import autoslug.fields
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255)),
                ('slug_categoria', autoslug.fields.AutoSlugField(default='general', editable=False, populate_from='nombre_categoria', unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'ordering': ('nombre_categoria',),
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_blog', models.CharField(default='', max_length=35, verbose_name='Titulo del blog')),
                ('campo_de_prueba', models.CharField(default='Hola', max_length=5)),
                ('subtitulo_blog', models.CharField(default='', max_length=50, verbose_name='Subtitulo del blog (Este campo puede estar vacio)')),
                ('imagen_blog', models.URLField(default='', max_length=600, verbose_name='URL de la Imagen')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='titulo_blog')),
                ('descripcion_breve', models.TextField(default='', verbose_name='Descripcion Breve')),
                ('contenido_blog', ckeditor.fields.RichTextField(verbose_name='Contenido del blog')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Publicacion')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='blog.categoria')),
            ],
        ),
    ]
