# Generated by Django 3.1.6 on 2021-02-19 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='subtitulo_blog',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Subtitulo del blog (Este campo puede estar vacio)'),
        ),
    ]
