# Generated by Django 3.1.6 on 2021-02-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210218_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo_blog',
            field=models.CharField(default='', max_length=300, verbose_name='Subtitulo del blog (Este campo puede estar vacio)'),
        ),
    ]
