# Generated by Django 3.1.6 on 2021-02-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210218_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subtitulo_blog',
            field=models.CharField(default='', max_length=50, verbose_name='Subtitulo del blog (Este campo puede estar vacio)'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='titulo_blog',
            field=models.CharField(default='', max_length=30, verbose_name='Titulo del blog'),
        ),
    ]
