# Generated by Django 3.1.6 on 2021-02-18 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechasImportantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(default='', max_length=50, verbose_name='Nombre del mes')),
                ('fechas', models.CharField(default='', max_length=200, verbose_name='Dia del mes. Ejemplo: Dia 02 - Dia Mundial de los humedales')),
            ],
        ),
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=150, verbose_name='Titulo de la noticia')),
                ('descripcion', models.CharField(default='', max_length=300, verbose_name='Descripcion de la noticia')),
                ('imagen', models.ImageField(upload_to='static/img/main')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de publicacion')),
                ('autor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
