# Generated by Django 3.1.6 on 2021-02-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de publicacion'),
        ),
    ]
