# Generated by Django 3.1.6 on 2021-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210218_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fechasimportantes',
            name='fechas',
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha1',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes. Ejemplo: Dia 02 - Dia Mundial de los humedales'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha10',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha11',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha12',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha13',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha14',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha15',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha16',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha17',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha18',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha19',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha2',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha20',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha21',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha22',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha23',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha24',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha25',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha26',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha27',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha28',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha29',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha3',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha30',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha31',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha4',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha5',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha6',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha7',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha8',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
        migrations.AddField(
            model_name='fechasimportantes',
            name='fecha9',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dia del mes'),
        ),
    ]
