# Generated by Django 3.1.6 on 2021-02-19 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210218_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fechasimportantes',
            old_name='mes',
            new_name='nombre',
        ),
    ]
