# Generated by Django 3.1.6 on 2021-02-19 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210218_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='descripcion',
            field=models.TextField(default='', verbose_name='Descripcion de la noticia'),
        ),
    ]
