# Generated by Django 3.1.6 on 2021-02-19 16:30

import autoslug.fields
import ckeditor.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210218_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='contenido',
            field=ckeditor.fields.RichTextField(default=django.utils.timezone.now, verbose_name='Contenido de la Noticia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticias',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='titulo'),
            preserve_default=False,
        ),
    ]
