# Generated by Django 3.1.6 on 2021-02-21 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210219_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(upload_to='static/img/main', verbose_name='Imagen (1600x900px)'),
        ),
    ]
