# Generated by Django 3.1.6 on 2021-02-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_galeria', models.CharField(default='', max_length=200, verbose_name='Titulo de la galeria')),
                ('imagen1', models.URLField(default='', max_length=600, verbose_name='URL de la Imagen')),
            ],
        ),
    ]
