# Generated by Django 3.1.6 on 2021-02-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='imagen10',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen2',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen3',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen4',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen5',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen6',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen7',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen8',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
        migrations.AddField(
            model_name='galeria',
            name='imagen9',
            field=models.URLField(default='', max_length=600, verbose_name='URL de la Imagen'),
        ),
    ]
